### ISSUE TITLE
Comparison with jpalardy/vim-slime?

### ISSUE THREAD

**Issue by nalzok** [axvr/zepl.vim#12]
Hi there,

How would you compare this project with https://github.com/jpalardy/vim-slime? I think it would be helpful to have a comparison section in README.md to help people decide if this is what they need.

**Comment by axvr** [comment]
Hi, I've added a new section to the README "[Why use Zepl?](https://github.com/axvr/zepl.vim#why-use-zepl)" but I intentionally didn't make any comparisons to specific alternatives such as vim-slime, so I'll explain some of the differences here:

- Zepl contains less than 1/3rd of the code of vim-slime while having exactly the same core functionality.
- Zepl contains twice the amount of documentation, and that documentation is more useful.
- Zepl only uses Vim's (and Neovim's) `:terminal` to host the REPL, unlike vim-slime which can additionally use many others, e.g. Tmux and GNU Screen.
- Zepl's [`gz` operator](https://github.com/axvr/zepl.vim#sending-text-to-the-repl) behaves like standard Vim operators such as `d`, `c` and `gq`.   Vim-slime's `ctrl-c ctrl-c` is far less capable and awkward in comparison.
- Zepl is newer and significantly less popular than vim-slime.
- Zepl contains (and has contained) fewer bugs than vim-slime (and most, if not all, other REPL plugins).
- Zepl contains extra features through [community contributed extensions](https://github.com/axvr/zepl.vim#additional-functionality), but they are switched off by default.
- Zepl is much more configurable, but doesn't provide any [per-language defaults](https://github.com/axvr/zepl.vim#set-default-repls).

I'm more than happy to explain any of these further, or even list the differences with other REPL plugins.
