### ISSUE TITLE
Any way to hide an open repl?

### ISSUE THREAD

**Issue by pfernandez** [axvr/zepl.vim#13]
Nice work on this plugin! I see that you can `:hide Repl` and show it again with `:Repl`, but once it's open, `<c-w> c` gives the error `E948: Job still running (add ! to end the job)`. Is this a known limitation, or do you think this could be due to a problem with my personal vimrc settings?

**Comment by axvr** [comment]
~~Hi, `<C-w> q` or `<C-w> :q` should do what you want.~~

~~See: https://vimhelp.org/windows.txt.html#CTRL-W_q~~

Correction below.

**Comment by axvr** [comment]
Oh, actually I think you might need to add `set hidden` in your vimrc.

See: [`:help 'hidden'`](https://vimhelp.org/options.txt.html#%27hidden%27)

**Comment by pfernandez** [comment]
That was it, thanks! In case you decide to add a note about this to the readme/docs, I'm using regular vim (not neovim).

**Comment by axvr** [comment]
Excellent!  I've added a note of that to the doc and README.
