### ISSUE TITLE
Repl window flashes open, then disappears

### ISSUE THREAD

**Issue by cameronroe7** [axvr/zepl.vim#17]
Hello,

I've been unable to use this plugin because whenever I type `:Repl julia` (or just `:Repl` in a Julia file) the REPL window is only open for a frame. I get a message of the form 

`"zepl: julia [running]" [Modified] --No lines in buffer--`

I've tried using a clean .vimrc with just the Julia package and this one and I have no luck.

**Comment by axvr** [comment]
Hi.  Usually this means either:

1. Vim couldn't find the `julia` command on the `PATH`.

2. The Julia REPL failed to start.

To help debug this I need some more info about your system.

1. What OS are you using?  (+ If you are on Windows are you using WSL?)
2. Vim or Neovim (+ version)?
3. Does the Julia REPL start if you run this command in Vim:

   ```vim
   :terminal julia
   ```

**Comment by cameronroe7** [comment]
Hey, thanks for your quick response!

1. Linux Mint 20.3
2. Vim 8.1.3741
3. No, I get the error `executing job failed: no such file or directory`. If I launch Julia through bash it works however.

**Comment by axvr** [comment]
Hm...  A few more questions:

1. How did you install Julia?  `sudo apt install julia`?
2. Do you start Vim from the terminal?  I.e. open a terminal, run `vim`?
3. In Bash, what is the output of this `which julia`?
4. In Bash, what is the output of this `alias julia`?
5. In Bash, what is the output of this `echo $PATH`?
6. In Vim, what is the output of this `:!echo $PATH`?
7. In Vim, what is the output of this `:set shell?`

**Comment by cameronroe7** [comment]
Thanks so much :) I just reinstalled Julia and symlinked the executable file for the repl into my `/usr/bin` folder, whereas before I had added the download folder (in my home directory) itself into my PATH. Now everything works great. 

Maybe it was an issue with permissions? It's weird, because I had used the REPL in the terminal with no problem before.

**Comment by axvr** [comment]
Excellent!
