### ISSUE TITLE
Send carriage returns in REPL?

### ISSUE THREAD

**Issue by reckoner** [axvr/zepl.vim#2]
The plugin works but  does not seem to  push the carriage returns. All of the sent output is on one line in the Python REPL.

**Comment by axvr** [comment]
Would you mind giving some information about your environment such as:
- Vim, gVim or Neovim (+ version)
- Operating system (+ version)
- Python version

**Comment by reckoner** [comment]
gVim 8.1 on Windows 10 1909. I tried with several Python versions and no carriage returns are sent to the REPL window.

**Comment by axvr** [comment]
I've pushed a fix.  Please let me know if it is still broken.

**Comment by reckoner** [comment]
Trailing carriage returns at the end of an indented python block still do not work but single lines do!

**Comment by axvr** [comment]
Full Python support has now been merged, please install the latest version and run `:help zepl-python` for info on how to enable it.
