### ISSUE TITLE
Running from visual mode should jump to end of block

### ISSUE THREAD

**Issue by rafaqz** [axvr/zepl.vim#22]
It took me a while to work this out:

```vim
vmap <silent> gz <Plug>ReplSend_Visual<CR>gv<Esc>
```

But I have the feeling most users want to jump to the end of a visual block after running it, not the start. So this could be a better default.

**Comment by axvr** [comment]
Hi @rafaqz, while I personally agree that it might be a more useful for the command to behave that way, it unfortunately would make it inconsistent with other Vim commands.  (E.g. `yip`, `vipy`, `vip>`, notice that the cursor will always move to the start.)

As one of my goals has been to make Zepl.vim feel like part of Vim, I won't change the default to something inconsistent with Vim's own mappings.

However, if you want to change Vim's defaults to not move the cursor at all (even for the `gz` command), you can copy the code snippet from this article into your Vim config: https://vimways.org/2019/making-things-flow/#don-t-break-my-flow
