### ISSUE TITLE
Extra carriage returns in Julia

### ISSUE THREAD

**Issue by gustaphe** [axvr/zepl.vim#3]
I'm using vim+zepl in PowersHell on Windows 10 (can reproduce it in cmd as well).
`:Repl python` followed by `:ReplSend 1+2` gives

    >>>1+2
    3
    >>>
but `:Repl julia` followed by `:ReplSend 1+2` gives

    julia>1+2
    3
    
    julia>
    
    julia>

(with an extra prompt line)
I'm guessing this is a `\r\n` error like always (some day we'll stop having to pay for that lapse of judgement...), but do you think there is a way to fix it? It looks like unneccessary clutter.

This works the same with the movement and visual send commands.

**Comment by axvr** [comment]
Thanks for reporting this.  Indeed it was a problem caused by `\r\n`.  It should now be fixed in latest version.  Please let me know if the problem persists.

Edit: also if you're using Python, please see: `:help zepl-python` for better Python support (I still need to add this to the README).

**Comment by gustaphe** [comment]
Perfect. Nice (and quick) work!

Sorry to go off topic, but when you do add that, consider suggesting it as a `ftplugin/python.vim` addition rather than a `.vimrc` addition.
