### ISSUE TITLE
creats extra line in neovim but not in vim

### ISSUE THREAD

**Issue by Gavinok** [axvr/zepl.vim#4]
When using neovim an extra line is inserted into the repl.

For example:
In vim

![2020-04-02_21:52:59](https://user-images.githubusercontent.com/34443260/78322701-baba3e00-752c-11ea-82a9-5b032991e31e.png)

When the same command is run in neovim
![2020-04-02_21:52:00](https://user-images.githubusercontent.com/34443260/78322646-92324400-752c-11ea-96a2-b7acc37faafc.png)

This issue persists in other repls as well.

**Comment by axvr** [comment]
This is now fixed in the latest version.  Sorry this took so long, I've been rather busy recently.

P.S. for better Python support in zepl, see `:help zepl-python`.
