### ISSUE TITLE
Adding a `g:repl_config` to avoid all the autocmds

### ISSUE THREAD

**Issue by Gavinok** [axvr/zepl.vim#6]
It would be nice if we could use something like `g:repl_config` to replace `b:repl_config` that follows the following format
```vim
let g:repl_config = {
			\'javascript': { 'cmd': 'node'},
			\'scheme':     { 'cmd': 'racket'},
			\'fennel':     { 'cmd': 'fennel'}
			\}
```
this way we can just have `:Repl` default to one of these filetypes if they exist. I don't think this needs to replace `b:repl_config` but having all those autocmds just for something that could be done only when needed would be great.

**Comment by Gavinok** [comment]
obviously for filetypes where you have a ftplugin then it makes sense to just add `b:repl_config` but most langs I and most others probably work with probably don't need a dedicated file.

**Comment by axvr** [comment]
Added.  Please let me know if you encounter any problems with it.
